default_stages: [commit]
repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
        verbose: true
      - id: go-imports
        args: [-l, -d, -w]
        verbose: true
      - id: go-mod-tidy
        verbose: true
      - id: golangci-lint-mod
        verbose: true
