// Code generated by mockery v2.9.4. DO NOT EDIT.

package species

import mock "github.com/stretchr/testify/mock"

// repositoryMock is an autogenerated mock type for the repositorier type
type repositoryMock struct {
	mock.Mock
}

// delete provides a mock function with given fields: id
func (_m *repositoryMock) delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// getAll provides a mock function with given fields:
func (_m *repositoryMock) getAll() ([]Species, error) {
	ret := _m.Called()

	var r0 []Species
	if rf, ok := ret.Get(0).(func() []Species); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Species)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// getById provides a mock function with given fields: id
func (_m *repositoryMock) getById(id string) (*Species, error) {
	ret := _m.Called(id)

	var r0 *Species
	if rf, ok := ret.Get(0).(func(string) *Species); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Species)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// save provides a mock function with given fields: sp
func (_m *repositoryMock) save(sp *Species) (*Species, error) {
	ret := _m.Called(sp)

	var r0 *Species
	if rf, ok := ret.Get(0).(func(*Species) *Species); ok {
		r0 = rf(sp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Species)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Species) error); ok {
		r1 = rf(sp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// update provides a mock function with given fields: sp
func (_m *repositoryMock) update(sp *Species) error {
	ret := _m.Called(sp)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Species) error); ok {
		r0 = rf(sp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
