---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: using-gin
  name: using-gin
data:
  PORT: "8080"
  DATABASE_URL: "postgres://postgres:postgres@172.25.0.2:5432/postgres"
  GIN_MODE: "release"