---
apiVersion: v1
kind: Service
metadata:
  name: using-gin-svc
spec:
  selector:
    app: using-gin
  type: NodePort
  sessionAffinity: None
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000
    protocol: TCP
