basePath: /
host: localhost:8080
info:
  contact: {}
  title: Natural History Museum API documentation
  version: 1.0.0
paths:
  /status/health:
    get:
      description: 'This returns a JSON {"status": "OK"} with a status 200 if the
        server is up'
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Returns OK if the server is up
      tags:
      - health
swagger: "2.0"
