basePath: /
definitions:
  species.Species:
    properties:
      class:
        example: Amphibia
        type: string
      family:
        example: Dendrobatidae
        type: string
      genus:
        example: Phyllobates
        type: string
      id:
        example: 996ff476-09bc-45f8-b79d-83b268de2485
        type: string
      kingdom:
        example: Animalia
        type: string
      order:
        example: Anura
        type: string
      phylum:
        example: Chordata
        type: string
      scientific_name:
        example: Phyllobates terribilis
        type: string
    required:
    - class
    - family
    - genus
    - kingdom
    - order
    - phylum
    - scientific_name
    type: object
host: localhost:8080
info:
  contact: {}
  title: Natural History Museum API documentation
  version: 1.0.0
paths:
  /health:
    get:
      description: 'This returns a JSON {"status": "OK"} with a status 200 if the
        server is up'
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Returns OK if the server is up
      tags:
      - health
  /species:
    get:
      consumes:
      - application/json
      description: Retrieves all species from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/species.Species'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get all species
      tags:
      - species
    post:
      consumes:
      - application/json
      description: Saves the species information into database
      parameters:
      - description: Species Payload
        in: body
        name: species
        required: true
        schema:
          $ref: '#/definitions/species.Species'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/species.Species'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Saves the given species
      tags:
      - species
  /species/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes the species information with the given id from database
      parameters:
      - description: Species ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Deletes the species with the given id
      tags:
      - species
    get:
      consumes:
      - application/json
      description: Retrieves the species from database with the given id
      parameters:
      - description: Species ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/species.Species'
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get species with the given id
      tags:
      - species
    put:
      consumes:
      - application/json
      description: Updates the species information with the given id in the database
      parameters:
      - description: Species Payload
        in: body
        name: species
        required: true
        schema:
          $ref: '#/definitions/species.Species'
      - description: Species ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Updates the species with the given id
      tags:
      - species
swagger: "2.0"
